import type React from "react"
import { Inter } from "next/font/google"
import "./globals.css"
import { dir } from "i18next"
import { languages } from "@/i18n/settings"
import { NextIntlClientProvider } from "next-intl"
import { notFound } from "next/navigation"
import { Toaster } from "@/components/ui/toaster"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export function generateStaticParams() {
  return languages.map((locale) => ({ locale }))
}

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode
  params: { locale: string }
}) {
  // Validate that the incoming `locale` parameter is valid
  if (!languages.includes(locale as any)) {
    notFound()
  }
  return (
    <html lang={locale} dir={dir(locale)}>
      <body className={inter.className}>
        <NextIntlClientProvider
          locale={locale}
          messages={
            // @ts-expect-error
            (await import(`../../messages/${locale}.json`)).default
          }
        >
          {children}
          <Toaster />
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
